version: "3.8"

services:
  nginx:
    image: nginx:1.25.3
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    networks:
      - shiny-network
  identity:
    image: quay.io/keycloak/keycloak:21.0.2
    command: ['start-dev']
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY: ${KC_PROXY}
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HTTP_PORT: ${KC_HTTP_PORT}
    depends_on:
      - db-postgres
    networks:
      - shiny-network
  db-postgres:
    image: debezium/postgres:15-alpine
    build: ./docker/postgres
    hostname: ${POSTGRES_HOST}
    container_name: db-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker/postgres/postgresql.conf.sample:/usr/share/postgresql/postgresql.conf.sample
      - ./docker/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres:/var/lib/postgresql/data
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shiny-network
  copilot-api:
    build: ./copilot-api
    ports:
      - "${COPILOT_API_PORT}:8000"
    # depends_on:
    #   - db-mongo
    networks:
      - shiny-network
  # db-mongo:
  #   image: mongo:latest
  #   container_name: db-mongo
  #   ports:
  #     - "{MOOMONGO_PORT}:27017"
  #   volumes:
  #     - ./mongo-db-data:/data/db

volumes:
  mongo-db-data:
  postgres:

networks:
  shiny-network:
    driver: bridge
    name: shiny-network