name: Shiny Gateway service ci

on:
  push:
    branches: ["main"]
    paths:
      - "shiny-gateway/**"
      - ".github/workflows/shiny-gateway-ci.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "shiny-gateway/**"
      - ".github/workflows/shiny-gateway-ci.yaml"

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker Images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          context: ./shiny-gateway
          push: true
          tags: ghcr.io/ngtrdai/shiny-gateway:latest
